name: Windows Build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.1'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          install-deps: 'true'
          modules: 'qtwebengine qtwebchannel qtpositioning' 
      - name: Configure Project
        run: qt-cmake -S . -B ./ccbuild11
      - name: Build Project
        working-directory: ./ccbuild11
        run: cmake --build .
      - name: LS
        run: ls 
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'release.zip'
      - name: LS
        run: ls 
      # - name: Zip the Build
      #   run: zip -r test ./build/ 
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 0.04
          name: Release0.04
          body: TODO New Release.
          draft: false
          prerelease: false
          files: |
            release.zip
            LICENSE 